### ISSUE TITLE
Requests for Micah :)

### ISSUE THREAD

**Issue by william-fiset** [MicahAndWill/SublimeAddons#1]
- [x] isSquare() method
- [x]  Sieve of Eratosthenes
- [ ] *Generic* Depth first Search
- [x] *Generic* Dijkstra's algorithm

~~factors of a number (Not the prime factors the regular factors).~~ (unless you want to make a faster one)

**Comment by micahstairs** [comment]
Generic depth first search is trivial, so I am closing this issue.
